import mongoose from 'mongoose';

const propertySchema = new mongoose.Schema({
    title: { type: String, required: true },
    sqft: { type: Number, required: true },
    bedrooms: { type: Number, required: true },
    bathrooms: { type: Number, required: true },
    location_score: { type: Number, required: true, min: 1, max: 10 },
    age: { type: Number, required: true, min: 0 },
    price: { type: Number, required: true }, // Predicted price from AI model
    persona: { type: String, default: null },
    persona_cluster: { type: Number, default: null },
    model_version: { type: String, default: '1.0' },
    isAiGenerated: { type: Boolean, default: false }, // Track if generated by AI prediction
    source: { type: String, default: 'manual' }, // 'ai', 'manual', 'wishlist'
    ownerId: { 
        type: mongoose.Schema.Types.ObjectId, 
        ref: 'user',
        required: true 
    },
    createdAt: { type: Date, default: Date.now },
    updatedAt: { type: Date, default: Date.now },
});

// Prevent model overwrite issues in serverless / hot-reload environments
export default mongoose.models.Property || mongoose.model('Property', propertySchema);
